---
- name: Install common packages
  apt: name={{ item }} state=present
  with_items:
   - vim
   - curl
   - git
   - python
   - python3
   - python-setuptools
   - apt-transport-https

- name: Remove useless packages
  apt: name={{ item }} state=absent purge=yes autoremove=yes force=yes
  with_items:
   - exim4
   - exim4-base
   - exim4-config

- name: stop nfs-common
  systemd: name=nfs-common state=stopped enabled=no
  changed_when: false

- name: stop rpcbind
  systemd: name=rpcbind state=stopped enabled=no
  changed_when: false

- name: install pip
  easy_install: name=pip state=latest
  changed_when: false

- name: install python packages
  pip: name={{ item }} state=latest
  with_items:
    - requests
    - influxdb
