---
- name: install system updates
  apt: upgrade=dist update_cache=yes

- name: Install common packages
  apt: name={{ item }} state=present
  with_items:
   - vim
   - curl
   - git
   - python
   - python3
   - python-setuptools
   - apt-transport-https

- name: Remove useless packages
  apt: name={{ item }} state=absent purge=yes autoremove=yes force=yes
  with_items:
   - exim4
   - exim4-base
   - exim4-config

- name: Check if nfs-common exists
  stat: path=/etc/init.d/nfs-common
  register: nfs_status

- name: stop nfs-common
  systemd: name=nfs-common state=stopped enabled=no
  when: nfs_status.stat.exists
  changed_when: false

- name: Check if rpcbind exists
  stat: path=/etc/init.d/rpcbind
  register: rpcbind_status

- name: stop rpcbind
  systemd: name=rpcbind state=stopped enabled=no
  when: rpcbind_status.stat.exists
  changed_when: false

- name: Check if hciuart exists
  stat: path=/lib/systemd/system/hciuart.service
  register: hciuart_status

- name: stop hciuart
  systemd: name=hciuart state=stopped enabled=no
  when: hciuart_status.stat.exists
  changed_when: false

- name: install pip
  easy_install: name=pip state=latest
  changed_when: false

- name: install python packages
  pip: name={{ item }} state=latest
  with_items:
    - requests
    - influxdb

- name: Install ntp
  apt: name=ntp state=present
  tags: ntp

- name: Configure ntp file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp
