---
- name: Check if datasource is present
  uri:
    url: http://localhost:3000/api/datasources/name/{{ db_name }}
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    force_basic_auth: yes
    status_code: 200,404
  register: grafana_status
  changed_when: false

- name: Create Datasource if not present
  uri:
    url: http://localhost:3000/api/datasources
    method: POST
    user: "{{ grafana_username }}"
    password: "{{ grafana_password }}"
    force_basic_auth: yes
    body:
      name: "{{ db_name }}"
      type: "influxdb"
      url: "http://localhost:8086"
      access: "proxy"
      isDefault: true
      database: "{{ db_name }}"
      user: "{{ influxdb_username }}"
      password: "{{ influxdb_password }}"
    status_code: 200
    body_format: json
  when: grafana_status.status == 404
